### ISSUE TITLE
Existing classes on div are deleted

### ISSUE THREAD

**Issue by ubershmekel** [gfycat/gfycat.js#4]
Because a new div is created that replaces the original at https://github.com/gfycat/gfycat.js/blob/master/js/gfyObject.js#L227 it seems that it's impossible to set the class of the embeded gfycat without javascript. E.g. in

```<div class="myStyle gfyitem" data-title=true data-autoplay=true data-controls=false data-expand=false data-id="BleakLinearHen" ></div>```

The `myStyle` class will be omitted from the resulting div.

**Comment by m0k1** [comment]
Can you provide me some example code ? So i can try to fix this ?

**Comment by ubershmekel** [comment]
https://jsfiddle.net/ubershmekel/7Lz5a7do/1/

The expected alert would be `found: 1` but it does not find the class of the div.

**Comment by koshka** [comment]
Hey @ubershmekel, thanks for your feedback.
This issue is fixed in the latest release. 
Classes which you set to initial `gfyitem` won't be overwritten anymore.
Also you can use **any class** for initialization instead of `gfyitem`. This init class will be deleted from the element due to initialization logic (so this element won't be found more than once by `gfyCollection.scan()` method).
For more information please check [README.md](https://github.com/gfycat/gfycat.js/blob/master/README.md)
